import { useEffect,useState } from 'preact/hooks'; import type { User } from 'firebase/auth'; import { Plus,ArrowUpRight,TrendingUp,Wallet,Landmark,Pencil,Trash2,X,ShieldCheck,Cloud,Download,Search,LoaderCircle,Copy } from 'lucide-preact'; import type { Asset,AssetType,Movement,Pac } from '../types'; import { marketDataConfigured,searchMarket,type MarketResult } from '../market';
type Props={path?:string,default?:boolean}; const eur=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}); const types=['ETF','Azioni','Obbligazioni','Liquidità','Fondi pensione','Crypto','Immobili','Altro']; const quotedTypes=new Set(['ETF','Azioni','Obbligazioni','Crypto']); const colors=['#806dff','#38d9a9','#f5b84b','#ff718b','#59b5ff','#b78cff','#ff9564','#8b98a9']; const id=()=>crypto.randomUUID();
const Header=({title,sub,action}:{title:string,sub:string,action?:any})=><header><div><p class="eyebrow">PATRIMONIO PERSONALE</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>;
const decimalText=(value:number)=>Number.isFinite(value)?String(value).replace('.',','):'';
function DecimalInput({value,onValue,...props}:{value:number,onValue:(value:number)=>void,[key:string]:any}){
 const [text,setText]=useState(decimalText(value)),[editing,setEditing]=useState(false);
 useEffect(()=>{if(!editing)setText(decimalText(value))},[value,editing]);
 return <input {...props} type="text" inputMode="decimal" pattern="[0-9]+([\.,][0-9]+)?" value={text} onFocus={()=>setEditing(true)} onInput={e=>{const raw=e.currentTarget.value;if(!/^\d*(?:[\.,]\d*)?$/.test(raw))return;setText(raw);if(raw&&!/[\.,]$/.test(raw)){const parsed=Number(raw.replace(',','.'));if(Number.isFinite(parsed))onValue(parsed)}}} onBlur={()=>{setEditing(false);setText(decimalText(value))}}/>;
}
export function Dashboard({assets}:Props&{assets:Asset[]}){const total=assets.reduce((s,a)=>s+a.value,0),invested=assets.reduce((s,a)=>s+a.invested,0),groups=types.map((t,i)=>({name:t,value:assets.filter(a=>a.type===t).reduce((s,a)=>s+a.value,0),color:colors[i]})).filter(x=>x.value);return <><Header title="Buongiorno 👋" sub="Ecco come sta andando il tuo patrimonio."/><div class="kpis"><article class="hero-card"><span>Patrimonio totale</span><strong>{eur.format(total)}</strong><em><TrendingUp size={15}/> {invested?((total/invested-1)*100).toFixed(1):'0'}% rendimento totale</em></article><article><span>Capitale investito</span><strong>{eur.format(invested)}</strong><small><Wallet/> Somma dei versamenti</small></article><article><span>Plusvalenza</span><strong class="positive">{eur.format(total-invested)}</strong><small><ArrowUpRight/> Non realizzata</small></article></div><div class="grid2"><article><div class="card-title"><div><h2>Allocazione</h2><p>Distribuzione per tipologia</p></div></div><div class="allocation"><div class="donut" style={{background:`conic-gradient(${groups.map((g,i)=>`${g.color} ${groups.slice(0,i).reduce((s,x)=>s+x.value,0)/total*100}% ${groups.slice(0,i+1).reduce((s,x)=>s+x.value,0)/total*100}%`).join(',')})`}}><i><b>{groups.length}</b><small>categorie</small></i></div><div class="legend">{groups.map(g=><div><i style={{background:g.color}}/><span>{g.name}</span><b>{(g.value/total*100).toFixed(1)}%</b></div>)}</div></div></article><article><div class="card-title"><div><h2>Le tue posizioni</h2><p>Aggiornate di recente</p></div><a href="/assets">Vedi tutte</a></div><div class="positions">{assets.slice(0,5).map((a,i)=><div><i style={{background:colors[types.indexOf(a.type)]}}>{a.name[0]}</i><span><b>{a.name}</b><small>{a.type}</small></span><strong>{eur.format(a.value)}<small class={a.value>=a.invested?'positive':'negative'}>{a.invested?((a.value/a.invested-1)*100).toFixed(1):0}%</small></strong></div>)}</div></article></div></>}
export function Assets({assets,api}:Props&{assets:Asset[],api:any}){const [edit,setEdit]=useState<Asset|null>(null);return <><Header title="Il tuo patrimonio" sub="Tutte le posizioni, in un solo posto." action={<button class="primary" onClick={()=>setEdit({id:id(),name:'',type:'ETF',value:0,invested:0,quantity:0,averageUnitCost:0,currentUnitPrice:0,currency:'EUR',updatedAt:new Date().toISOString().slice(0,10)})}><Plus/> Aggiungi asset</button>}/><div class="table-card"><table><thead><tr><th>Asset</th><th>Tipologia</th><th>Valore attuale</th><th>Investito</th><th>Rendimento</th><th></th></tr></thead><tbody>{assets.map(a=><tr><td><b>{a.name}</b>{a.quantity!==undefined?<small class="asset-units">{a.quantity.toLocaleString('it-IT')} unità</small>:a.nominalValue!==undefined&&<small class="asset-units">Nominale {eur.format(a.nominalValue)}</small>}</td><td><span class="tag">{a.type}</span></td><td>{eur.format(a.value)}</td><td>{eur.format(a.invested)}</td><td class={a.value>=a.invested?'positive':'negative'}>{a.invested?((a.value/a.invested-1)*100).toFixed(1):0}%</td><td><button class="icon" onClick={()=>setEdit(a)}><Pencil/></button><button class="icon danger" onClick={()=>confirm('Eliminare questo asset?')&&api.deleteAsset(a.id)}><Trash2/></button></td></tr>)}</tbody></table>{!assets.length&&<Empty text="Nessun asset ancora. Aggiungi la tua prima posizione."/>}</div>{edit&&<AssetModal value={edit} getPrice={api.getMarketPrice} close={()=>setEdit(null)} save={(v:any)=>{api.saveAsset(v);setEdit(null)}}/>}</>}
function AssetModal({value,close,save,getPrice}:{value:Asset,close:()=>void,save:(x:Asset)=>void,getPrice:(result:MarketResult)=>Promise<number>}){
 const legacyBond=value.type==='Obbligazioni'&&value.purchasePrice===undefined;
 const legacyQuoted=value.type!=='Obbligazioni'&&quotedTypes.has(value.type)&&value.quantity===undefined;
 const initial=legacyBond?{...value,purchasePrice:100,nominalValue:value.invested,currentUnitPrice:value.invested?value.value/value.invested*100:100}:legacyQuoted?{...value,quantity:1,averageUnitCost:value.invested,currentUnitPrice:value.value}:value;
 const [v,setV]=useState<Asset>(initial);
 const bond=v.type==='Obbligazioni',quoted=quotedTypes.has(v.type),quantity=v.quantity||0,averageUnitCost=v.averageUnitCost||0,currentUnitPrice=v.currentUnitPrice||0,purchasePrice=v.purchasePrice||0,invested=v.invested||0,nominalValue=purchasePrice?invested/(purchasePrice/100):0;
 const submit=()=>save(bond?{...v,invested,purchasePrice,nominalValue,currentUnitPrice,value:nominalValue*(currentUnitPrice/100),quantity:undefined,averageUnitCost:undefined,updatedAt:new Date().toISOString().slice(0,10)}:quoted?{...v,quantity,averageUnitCost,currentUnitPrice,value:quantity*currentUnitPrice,invested:quantity*averageUnitCost,purchasePrice:undefined,nominalValue:undefined,updatedAt:new Date().toISOString().slice(0,10)}:{...v,quantity:undefined,averageUnitCost:undefined,currentUnitPrice:undefined,purchasePrice:undefined,nominalValue:undefined,ticker:undefined,exchange:undefined,marketCurrency:undefined,isin:undefined});
 return <Modal title={value.name?'Modifica asset':'Nuovo asset'} close={close}><form onSubmit={e=>{e.preventDefault();submit()}}>
  {quoted?<MarketLookup value={v} setValue={setV} getPrice={getPrice}/>:<label>Nome<input required value={v.name} onInput={e=>setV({...v,name:e.currentTarget.value})} placeholder="es. Conto deposito"/></label>}
  <label>Tipologia<select value={v.type} onChange={e=>setV({...v,type:e.currentTarget.value as AssetType})}>{types.map(t=><option>{t}</option>)}</select></label>
  {bond?<><div class="formrow"><label>Importo investito (€)<DecimalInput required value={invested} onValue={invested=>setV({...v,invested})}/></label><label>Prezzo di acquisto (%)<DecimalInput required value={purchasePrice} onValue={purchasePrice=>setV({...v,purchasePrice})}/></label></div><label>Prezzo corrente (%)<DecimalInput required value={currentUnitPrice} onValue={currentUnitPrice=>setV({...v,currentUnitPrice})}/></label><p class="hint">Valore nominale: <b>{eur.format(nominalValue)}</b> · Valore attuale: <b>{eur.format(nominalValue*(currentUnitPrice/100))}</b></p></>:quoted?<><label>Unità possedute<DecimalInput required value={quantity} onValue={quantity=>setV({...v,quantity})}/></label><div class="formrow"><label>Prezzo medio di carico (€)<DecimalInput required value={averageUnitCost} onValue={averageUnitCost=>setV({...v,averageUnitCost})}/></label><label>Prezzo corrente per unità (€)<DecimalInput required value={currentUnitPrice} onValue={currentUnitPrice=>setV({...v,currentUnitPrice})}/></label></div><p class="hint">Valore attuale: <b>{eur.format(quantity*currentUnitPrice)}</b> · Capitale investito: <b>{eur.format(quantity*averageUnitCost)}</b></p></>:<div class="formrow"><label>Valore attuale (€)<DecimalInput required value={v.value} onValue={value=>setV({...v,value})}/></label><label>Capitale investito (€)<DecimalInput required value={v.invested} onValue={invested=>setV({...v,invested})}/></label></div>}
  <label>Note<textarea value={v.notes} onInput={e=>setV({...v,notes:e.currentTarget.value})}/></label><button class="primary wide">Salva asset</button>
 </form></Modal>
}
function MarketLookup({value,setValue,getPrice}:{value:Asset,setValue:(v:Asset)=>void,getPrice:(result:MarketResult)=>Promise<number>}){
 const [term,setTerm]=useState(value.isin||value.ticker||value.name),[results,setResults]=useState<MarketResult[]>([]),[searching,setSearching]=useState(false),[loadingPrice,setLoadingPrice]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false);
 useEffect(()=>{if(term.trim().length<2||!open||value.ticker===term||value.isin===term){setResults([]);return}const controller=new AbortController(),timer=setTimeout(async()=>{setSearching(true);setError('');try{setResults(await searchMarket(term.trim(),controller.signal))}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{setSearching(false)}},1200);return()=>{clearTimeout(timer);controller.abort()}},[term,open,value.ticker,value.isin]);
 const choose=async(result:MarketResult)=>{setOpen(false);setResults([]);setTerm(result.isin||result.symbol);setError('');const kind=(result.instrument_type||'').toLowerCase();const type:AssetType=kind.includes('etf')?'ETF':kind.includes('crypto')?'Crypto':kind.includes('bond')?'Obbligazioni':'Azioni';const selected={...value,name:result.instrument_name||result.symbol,ticker:result.symbol,exchange:result.exchange,marketCurrency:result.currency,isin:result.isin,type,automaticPrice:result.priceAvailable!==false};if(result.priceAvailable===false){setValue(selected);setError('Titolo trovato nel catalogo ufficiale. Inserisci manualmente il prezzo corrente (%).');return}setLoadingPrice(true);try{const price=await getPrice(result);setValue({...selected,currentUnitPrice:price})}catch(e){setValue({...selected,automaticPrice:false});setError((e as Error).message)}finally{setLoadingPrice(false)}};
 return <label class="market-search">Ticker, nome o ISIN<div class="search-input"><Search/><input required value={term} onFocus={()=>setOpen(true)} onInput={e=>{const text=e.currentTarget.value;setTerm(text);setOpen(true);setValue({...value,name:text,ticker:undefined,exchange:undefined,marketCurrency:undefined,isin:undefined,automaticPrice:undefined})}} placeholder="es. VWCE, Apple, Bitcoin, IT000..."/>{(searching||loadingPrice)&&<LoaderCircle class="spin"/>}</div>{open&&results.length>0&&<div class="suggestions">{results.map(result=><button type="button" onClick={()=>choose(result)}><b>{result.symbol}</b><span>{result.instrument_name}</span><small>{[result.isin,result.exchange,result.currency].filter(Boolean).join(' · ')}</small></button>)}</div>}{value.ticker&&<small class="selected-market">{value.name} · {value.isin||value.ticker}{value.exchange?` · ${value.exchange}`:''}{loadingPrice?' · recupero prezzo…':''}</small>}{!marketDataConfigured&&<small class="market-warning">Il catalogo dei Titoli di Stato è attivo; configura Twelve Data per gli altri strumenti.</small>}{error&&<small class="market-error">{error}</small>}</label>
}
export function Movements({assets,movements,api}:Props&{assets:Asset[],movements:Movement[],api:any}){const [open,setOpen]=useState(false),[edit,setEdit]=useState<Movement|null>(null);return <><Header title="Movimenti" sub="Lo storico aggiorna quantità, prezzo medio e rendimento degli asset." action={<button class="primary" onClick={()=>setOpen(true)}><Plus/> Inserimento rapido</button>}/><div class="table-card"><table><thead><tr><th>Data</th><th>Asset</th><th>Tipo</th><th>Importo</th><th>Quantità</th><th>Prezzo unitario</th><th>Note</th><th></th></tr></thead><tbody>{[...movements].sort((a,b)=>b.date.localeCompare(a.date)).map(m=><tr><td>{new Date(m.date).toLocaleDateString('it-IT')}</td><td><b>{m.assetName}</b></td><td><span class="tag">{m.type}</span>{m.pacId&&<span class="auto">PAC</span>}</td><td>{eur.format(m.amount)}</td><td>{m.quantity?.toLocaleString('it-IT',{maximumFractionDigits:8})||'—'}</td><td>{m.quantity?eur.format(m.amount/m.quantity):'—'}</td><td>{m.notes}</td><td><button class="icon" onClick={()=>setEdit(m)} title="Modifica movimento"><Pencil/></button><button class="icon danger" onClick={()=>api.deleteMovement(m.id)} title="Elimina movimento"><Trash2/></button></td></tr>)}</tbody></table>{!movements.length&&<Empty text="I movimenti manuali e quelli generati dai PAC compariranno qui."/>}</div>{open&&<MovementModal assets={assets} close={()=>setOpen(false)} save={async(v:Movement[])=>{await api.saveMovements(v);setOpen(false)}}/>}{edit&&<MovementModal assets={assets} initial={edit} close={()=>setEdit(null)} save={async(v:Movement[])=>{await api.saveMovements(v);setEdit(null)}}/>}</>}
const movementTypes:Movement['type'][]=['Versamento','Acquisto','Vendita','Prelievo'];
const newMovement=(assets:Asset[],previous?:Movement):Movement=>({id:id(),assetId:previous?.assetId||assets[0]?.id||'',assetName:previous?.assetName||assets[0]?.name||'',type:previous?.type||'Versamento',amount:0,date:previous?.date||new Date().toISOString().slice(0,10),notes:''});
function MovementModal({assets,close,save,initial}:{assets:Asset[],close:()=>void,save:(rows:Movement[])=>Promise<void>,initial?:Movement}){
 const [rows,setRows]=useState<Movement[]>(initial?[{...initial}]:[newMovement(assets)]),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const update=(index:number,patch:Partial<Movement>)=>setRows(current=>current.map((row,i)=>i===index?{...row,...patch}:row));
 const add=()=>setRows(current=>[...current,newMovement(assets,current[current.length-1])]);
 const duplicate=(index:number)=>setRows(current=>{const copy={...current[index],id:id()};return [...current.slice(0,index+1),copy,...current.slice(index+1)]});
 const removeRow=(index:number)=>setRows(current=>current.length===1?[newMovement(assets)]:current.filter((_,i)=>i!==index));
 const submit=async()=>{setSaving(true);setError('');try{await save(rows)}catch{setError('Non è stato possibile salvare i movimenti. Riprova.');setSaving(false)}};
 return <Modal title="Inserimento rapido movimenti" close={close} wide><form class="bulk-form" onSubmit={e=>{e.preventDefault();submit()}}><div class="bulk-intro"><p>Per acquisti e vendite indica importo totale e quantità: il prezzo unitario viene calcolato automaticamente.</p><span>{rows.length} {rows.length===1?'movimento':'movimenti'}</span></div><div class="bulk-table"><div class="bulk-head"><span>Data</span><span>Asset</span><span>Tipo</span><span>Importo</span><span>Quantità</span><span>Prezzo/unità</span><span>Note</span><span/></div>{rows.map((row,index)=>{const trade=row.type==='Acquisto'||row.type==='Vendita';return <div class="bulk-row" key={row.id}><input aria-label="Data" required type="date" value={row.date} onInput={e=>update(index,{date:e.currentTarget.value})}/><select aria-label="Asset" required value={row.assetId} onChange={e=>{const asset=assets.find(x=>x.id===e.currentTarget.value);update(index,{assetId:asset?.id||'',assetName:asset?.name||''})}}>{assets.map(asset=><option value={asset.id}>{asset.name}</option>)}</select><select aria-label="Tipo" value={row.type} onChange={e=>{const type=e.currentTarget.value as Movement['type'];update(index,{type,quantity:type==='Acquisto'||type==='Vendita'?row.quantity:undefined})}}>{movementTypes.map(type=><option>{type}</option>)}</select><DecimalInput aria-label="Importo" required value={row.amount} onValue={amount=>update(index,{amount})}/>{trade?<DecimalInput aria-label="Quantità" required value={row.quantity||0} onValue={quantity=>update(index,{quantity})}/>:<span class="not-applicable">—</span>}<output class="unit-price">{trade&&row.quantity?eur.format(row.amount/row.quantity):'—'}</output><input aria-label="Note" value={row.notes||''} placeholder="facoltative" onInput={e=>update(index,{notes:e.currentTarget.value})}/><div class="row-actions"><button type="button" class="icon" onClick={()=>duplicate(index)} title="Duplica riga"><Copy/></button><button type="button" class="icon danger" onClick={()=>removeRow(index)} title="Elimina riga"><Trash2/></button></div></div>})}</div><button type="button" class="add-row" onClick={add}><Plus/> Aggiungi riga <small>mantiene i dati ricorrenti</small></button>{error&&<p class="form-error">{error}</p>}<div class="bulk-footer"><button type="button" class="secondary" onClick={close}>Annulla</button><button class="primary" disabled={!assets.length||saving||rows.some(row=>!row.assetId||!row.date||row.amount<=0||((row.type==='Acquisto'||row.type==='Vendita')&&(!row.quantity||row.quantity<=0)))}>{saving?<LoaderCircle class="spin"/>:null} Salva {rows.length} {rows.length===1?'movimento':'movimenti'}</button></div></form></Modal>}
export function Pacs({assets,pacs,api}:Props&{assets:Asset[],pacs:Pac[],api:any}){const [open,setOpen]=useState(false);return <><Header title="Piani di accumulo" sub="Automatizza la registrazione dei versamenti ricorrenti." action={<button class="primary" onClick={()=>setOpen(true)}><Plus/> Nuovo PAC</button>}/><div class="pac-grid">{pacs.map(p=><article class="pac"><div><i><Landmark/></i><span><b>{p.name}</b><small>{p.assetName}</small></span><button class="switch" className={p.active?'switch on':'switch'} onClick={()=>api.savePac({...p,active:!p.active})}><i/></button></div><strong>{eur.format(p.amount)}<small>/ mese</small></strong><p>Il giorno <b>{p.day}</b> di ogni mese · dal {new Date(p.startDate).toLocaleDateString('it-IT')}</p><div><span class="tag">{p.active?'Attivo':'In pausa'}</span><button class="icon danger" onClick={()=>api.deletePac(p.id)}><Trash2/></button></div></article>)}{!pacs.length&&<article class="empty pac-empty"><RepeatIcon/><h3>Crea il tuo primo PAC</h3><p>Le rate scadute vengono registrate automaticamente quando accedi.</p></article>}</div>{open&&<PacModal assets={assets} close={()=>setOpen(false)} save={(v:any)=>{api.savePac(v);setOpen(false)}}/>}</>}
const RepeatIcon=()=> <div class="bigicon">↻</div>;
function PacModal({assets,close,save}:{assets:Asset[],close:()=>void,save:any}){const [v,setV]=useState<any>({id:id(),name:'',assetId:assets[0]?.id||'',assetName:assets[0]?.name||'',amount:0,day:1,startDate:new Date().toISOString().slice(0,10),active:true});return <Modal title="Nuovo piano PAC" close={close}><form onSubmit={e=>{e.preventDefault();save(v)}}><label>Nome del piano<input required placeholder="es. PAC ETF globale" onInput={e=>setV({...v,name:e.currentTarget.value})}/></label><label>Asset collegato<select required onChange={e=>{const a=assets.find(x=>x.id===e.currentTarget.value);setV({...v,assetId:a?.id,assetName:a?.name})}}>{assets.map(a=><option value={a.id}>{a.name}</option>)}</select></label><div class="formrow"><label>Rata mensile (€)<input required min="1" step=".01" type="number" onInput={e=>setV({...v,amount:+e.currentTarget.value})}/></label><label>Giorno del mese<input required min="1" max="31" type="number" value={v.day} onInput={e=>setV({...v,day:+e.currentTarget.value})}/></label></div><label>Data di inizio<input required type="date" value={v.startDate} onInput={e=>setV({...v,startDate:e.currentTarget.value})}/></label><p class="hint">Se il giorno non esiste nel mese, verrà usato l'ultimo giorno disponibile.</p><button class="primary wide" disabled={!assets.length}>Crea PAC</button></form></Modal>}
export function Settings({user}:Props&{user:User|null}){return <><Header title="Impostazioni" sub="Account, dati e preferenze."/><div class="settings"><article><ShieldCheck/><div><h3>Privacy per utente</h3><p>Le regole del database consentono l'accesso solo al tuo identificativo Google. Gli altri utenti non possono leggere i tuoi dati.</p></div></article><article><Cloud/><div><h3>Sincronizzazione sicura</h3><p>I dati sono salvati su Firestore e disponibili su tutti i tuoi dispositivi autenticati.</p></div></article><article><Download/><div><h3>Esportazione dati</h3><p>L'esportazione CSV sarà disponibile in una prossima versione.</p></div></article>{user&&<p class="account">Account connesso: <b>{user.email}</b></p>}</div></>}
function Modal({title,close,children,wide=false}:{title:string,close:()=>void,children:any,wide?:boolean}){return <div class="overlay" onClick={e=>e.target===e.currentTarget&&close()}><div class={wide?'modal modal-wide':'modal'}><div><h2>{title}</h2><button class="icon" onClick={close}><X/></button></div>{children}</div></div>}; const Empty=({text}:{text:string})=><div class="empty"><div class="bigicon">＋</div><p>{text}</p></div>;
