import { render } from 'preact'; import { useEffect,useMemo,useState } from 'preact/hooks'; import Router from 'preact-router';
import { onAuthStateChanged,signInWithPopup, type User } from 'firebase/auth'; import { auth,configured,googleProvider } from './firebase';
import { watch,save,saveMany,remove,materializePacs,type Asset,type Movement,type Pac } from './store'; import { Layout } from './ui/Layout'; import { Dashboard,Assets,Movements,Pacs,Settings } from './ui/Pages'; import { appUrl } from './base'; import './style.css';
import { getEuroPrice,type MarketResult } from './market'; import { getCachedEuroPrice } from './quotes';
const demoAssets:Asset[]=[{id:'1',name:'VWCE',type:'ETF',value:32450,invested:27800,currency:'EUR',updatedAt:'2026-07-15'},{id:'2',name:'Conto deposito',type:'Liquidità',value:14800,invested:14800,currency:'EUR',updatedAt:'2026-07-10'},{id:'3',name:'Fondo pensione',type:'Fondi pensione',value:21900,invested:18500,currency:'EUR',updatedAt:'2026-07-01'},{id:'4',name:'BTP Valore',type:'Obbligazioni',value:11240,invested:11000,currency:'EUR',updatedAt:'2026-07-12'}];
const movementKey=(value?:string)=>value?.trim().toLocaleLowerCase('it-IT').replace(/\s+/g,' ')||'';
function assetsFromMovements(assets:Asset[],movements:Movement[]){return assets.map(asset=>{
 const linked=movements.filter(m=>m.assetId===asset.id||movementKey(m.assetName)===movementKey(asset.name)).sort((a,b)=>a.date.localeCompare(b.date));
 if(!linked.length)return asset;
 const trades=linked.filter(m=>m.type==='Acquisto'||m.type==='Vendita'),cashFlows=linked.filter(m=>m.type==='Versamento'||m.type==='Prelievo');
 const tradeNet=trades.reduce((total,m)=>total+(m.type==='Acquisto'?m.amount:-m.amount),0),cashNet=cashFlows.reduce((total,m)=>total+(m.type==='Versamento'?m.amount:-m.amount),0);
 const historicalInvested=Math.max(0,trades.some(m=>m.type==='Acquisto')?tradeNet:cashNet);
 const quantitiesComplete=trades.length>0&&trades.every(m=>m.quantity&&m.quantity>0);
 if(!quantitiesComplete)return {...asset,invested:historicalInvested};
 let quantity=0,cost=0;
 for(const trade of trades){const units=trade.quantity!;if(trade.type==='Acquisto'){quantity+=units;cost+=trade.amount}else{const sold=Math.min(units,quantity),average=quantity?cost/quantity:0;cost=Math.max(0,cost-sold*average);quantity=Math.max(0,quantity-units)}}
 const averageUnitCost=quantity?cost/quantity:0;
 if(asset.type==='Obbligazioni'){const value=asset.currentUnitPrice===undefined?asset.value:quantity*asset.currentUnitPrice/100;return {...asset,nominalValue:quantity,invested:cost,purchasePrice:averageUnitCost*100,value}}
 const value=asset.currentUnitPrice===undefined?asset.value:quantity*asset.currentUnitPrice;
 return {...asset,quantity,averageUnitCost,invested:cost,value};
})}
function App(){const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[assets,setAssets]=useState<Asset[]>(configured?[]:demoAssets),[movements,setMovements]=useState<Movement[]>([]),[pacs,setPacs]=useState<Pac[]>([]),[theme,setTheme]=useState(localStorage.theme||'dark'),[currentPath,setCurrentPath]=useState(location.pathname);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.theme=theme},[theme]);
 useEffect(()=>{if(!user)return; const stops=[watch<Asset>(user.uid,'assets',setAssets),watch<Movement>(user.uid,'movements',setMovements),watch<Pac>(user.uid,'pacs',v=>{setPacs(v);materializePacs(user.uid,v)})];return()=>stops.forEach(x=>x())},[user]);
 useEffect(()=>{if(!user)return;let cancelled=false;const refresh=async()=>{for(const asset of assets.filter(a=>a.ticker&&a.automaticPrice!==false&&(a.quantity!==undefined||a.nominalValue!==undefined))){const result:MarketResult={symbol:asset.ticker!,instrument_name:asset.name,exchange:asset.exchange,currency:asset.marketCurrency,instrument_type:asset.type,isin:asset.isin};try{const price=await getCachedEuroPrice(user.uid,result);if(!cancelled&&Math.abs(price-(asset.currentUnitPrice||0))>.000001){const value=asset.type==='Obbligazioni'?(asset.nominalValue||0)*(price/100):(asset.quantity||0)*price;await save(user.uid,'assets',{...asset,currentUnitPrice:price,value,updatedAt:new Date().toISOString().slice(0,10)})}}catch{/* Il prezzo manuale resta invariato se i provider non rispondono. */}}};void refresh();const timer=setInterval(refresh,60*60*1000);return()=>{cancelled=true;clearInterval(timer)}},[user,assets]);
 const calculatedAssets=useMemo(()=>assetsFromMovements(assets,movements),[assets,movements]);
 const api=useMemo(()=>({saveAsset:(v:Asset)=>user&&save(user.uid,'assets',v),deleteAsset:(id:string)=>user&&remove(user.uid,'assets',id),saveMovement:(v:Movement)=>user&&save(user.uid,'movements',v),saveMovements:(v:Movement[])=>user&&saveMany(user.uid,'movements',v),deleteMovement:(id:string)=>user&&remove(user.uid,'movements',id),savePac:(v:Pac)=>user&&save(user.uid,'pacs',v),deletePac:(id:string)=>user&&remove(user.uid,'pacs',id),getMarketPrice:(result:MarketResult)=>user?getCachedEuroPrice(user.uid,result):getEuroPrice(result)}),[user]);
 if(loading)return <div class="center">Caricamento…</div>; if(configured&&!user)return <Login/>;
 return <Layout user={user} theme={theme} setTheme={setTheme} currentPath={currentPath}><Router onChange={({url})=>setCurrentPath(url)}><Dashboard path={appUrl()} assets={calculatedAssets}/><Assets path={appUrl('assets')} assets={calculatedAssets} api={api}/><Movements path={appUrl('movements')} assets={assets} movements={movements} api={api}/><Pacs path={appUrl('pacs')} assets={assets} pacs={pacs} api={api}/><Settings path={appUrl('settings')} user={user}/><Dashboard default assets={calculatedAssets}/></Router></Layout>}
function Login(){return <main class="login"><div class="brandmark">P</div><p class="eyebrow">IL TUO PATRIMONIO, IN CHIARO</p><h1>Ogni euro.<br/><span>Sotto controllo.</span></h1><p class="lead">Una vista semplice e privata su investimenti, liquidità e obiettivi. I tuoi dati restano soltanto tuoi.</p><button class="google" onClick={()=>signInWithPopup(auth,googleProvider)}><b>G</b> Continua con Google</button><small>Accedendo accetti l'informativa privacy. Non condividiamo dati con terze parti.</small></main>}
render(<App/>,document.getElementById('app')!);
